[package]
name = "FerriteChatter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fc"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
clap = "4.2.1"
inquire = "0.6.1"
openai = "1.0.0-alpha.8"
tokio = { version="1.27.0", features=["full"] }
